[ 2024-11-08 18:11:17,241 ] - 20 root - INFO - Entered the initiate_data_ingestion method
[ 2024-11-08 18:11:17,242 ] - 23 root - INFO - Successfully ran the initiate_data_ingestion method
[ 2024-11-08 18:11:17,248 ] - 38 root - ERROR - [Errno 2] No such file or directory: 'notebooks\\data\\stud.csv'
Traceback (most recent call last):
  File "c:\Users\Marina\Desktop\ML Operations\0 - KrishNaik Course\20__end_to_end_ds_project_implementation_multiple_aws_azure_deployment\my_project\src\components\data_ingestion.py", line 24, in initiate_data_ingestion
    dataframe = pd.read_csv(self.ingestion_config.raw_data_path)
  File "c:\Users\Marina\.conda\envs\ml_project\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "c:\Users\Marina\.conda\envs\ml_project\lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "c:\Users\Marina\.conda\envs\ml_project\lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "c:\Users\Marina\.conda\envs\ml_project\lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "c:\Users\Marina\.conda\envs\ml_project\lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'notebooks\\data\\stud.csv'
